{"componentChunkName":"component---src-templates-post-jsx","path":"/java-exception/","result":{"data":{"site":{"siteMetadata":{"title":"modisfive's 블로그"}},"markdownRemark":{"id":"019c6b3f-e536-562b-aa39-7fcc9e7c1714","excerpt":"프로그램이 자바 언어의 제약을 벗어난다면, JVM은 Exception으로 프로그램에게 에러를 발생시킨다. 예시로 정해진 배열의 범위를 벗어나 접근하는 경우가 있다. 또한, 프로그램은 를 사용해서 명시적으로 Exception을 발생시킬 수 있다. 이러한 자바의 Exception의 종류와 동작 방식 등에 대해 알아보자. Exception의 종류 Excepti…","html":"<p>프로그램이 자바 언어의 제약을 벗어난다면, JVM은 Exception으로 프로그램에게 에러를 발생시킨다. 예시로 정해진 배열의 범위를 벗어나 접근하는 경우가 있다. 또한, 프로그램은 <code class=\"language-text\">throws</code>를 사용해서 명시적으로 Exception을 발생시킬 수 있다. 이러한 자바의 Exception의 종류와 동작 방식 등에 대해 알아보자.</p>\n<h2>Exception의 종류</h2>\n<figure>\n   <span class='gatsby-resp-image-wrapper' style='position: relative; display: block; margin-left: auto; margin-right: auto; max-width: 400px; margin-bottom: 16px;'>\n      <a class='gatsby-resp-image-link' href='/static/a32d8b4866f9de65f0a75be0e86712ff/d9f49/java-exception-hierarchy.png' style='display: block' target='_blank' rel='noopener'>\n    <span class='gatsby-resp-image-background-image' style=\"padding-bottom: 81.17647058823529%; position: relative; bottom: 0; left: 0; background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAQCAIAAACZeshMAAAACXBIWXMAABJ0AAASdAHeZh94AAADKElEQVR42l1RWU9TQRi9L/wCDaLUaEtsK3V7MxpN1Oi7Pmh8kBgTHlyi4v7gglFRkBBkMZHWKChSFyCIEDEqgkApvWytUIrVUqCoCC3UtvfOPg6tipqczEwy3/m+c84nUU4SwBRTCryTkereYF1/qP5DuLZvqs4VHp3+wRgiv8v+hjR3EUgQUGJRCsLtnqnjlcNH78pZFc7MouaTVm/PSAiiGKKEcCrwPxlzjhhTEeKchxQyPE28QTw8jT4HoS8IFIQpUcVwzkUhZBzPkwlSwYms8J7doYx96q6d+HYxEz0YZgx3B9RXnkjjh5l6V7jeGWp0RxuHQGAWcCGBJcgghnQ6ryQ5kpJCkkT37oVciIEIqeW9+Eztt8Nl9kN3bJnFLaeqPDltzPVFFWScIAvDoK4Gl99HlQ9QxT1gtxFBjo/+OIP7p8nALGvzTvUHoq6JaJvn24wq9BMyH5hoFYeIjs2G2PgYnwggv4+O+/jECA/46PeA+GQUIRhjf2X2K20KYsLprNXauSBlMM3o1K7o0+ndOoMzzdibnPo144BoLVaiQJX+Q6aIYiDIIieloWFo/Ubfth2ftm4f3LDJu3mLZ9sOz4bNk6fPUc4SZBI3nICYzP7Iju+MQsaE7ZloBAlrnDEKOANx2SJFZS6Q35CgowtmXya5N2FOLs3NAznX8Y25B80vwFdzVOvj7q/4zWfU6keto/SdD4uzZQQ1+1CHX5Xg/XK4cEnfUu37FI0tRdO+KNWeoulYlCovWaYka3DGfusgKpR53tvQhWrvtZeT2c/9+a2RIplbHEBCVquiN8mr1rYYTB0rTe+MAumtRpPNtOaHYRU9cvTpgFLYppx/6DicX51V2nQw72n2E1eJHZV3K5JaVTWq03evXtdsNL3Qr3xtSBePJkO6aDesM8SOHKuSp85WyFdrh67UDF181HP52cCVGvelZ25LR3BOdmzBYiXNiLQGRauPLF8hTqA1xNKM0WQNyNj/2E0K7LxEZkUOfquLFjlYcRcv7OIWGUrQ5UQlpdhsQWVmXGaGZWaUgNmCS2+DhhcDk8DmB/ZRYB+bR+cY6AkoPwHWo+3goq/8OgAAAABJRU5ErkJggg=='); background-size: cover; display: block;\"></span>\n  <img class='gatsby-resp-image-image' alt='java exception hierarchy' title='' src='/static/a32d8b4866f9de65f0a75be0e86712ff/d9f49/java-exception-hierarchy.png' srcset='/static/a32d8b4866f9de65f0a75be0e86712ff/e7570/java-exception-hierarchy.png 170w,\n/static/a32d8b4866f9de65f0a75be0e86712ff/f46e7/java-exception-hierarchy.png 340w,\n/static/a32d8b4866f9de65f0a75be0e86712ff/d9f49/java-exception-hierarchy.png 400w' sizes='(max-width: 400px) 100vw, 400px' style='width:100%;height:100%;margin:0;vertical-align:middle;position:absolute;top:0;left:0;' loading='lazy' decoding='async'>\n  </a>\n    </span>\n   <figcaption>출처: https://www.javamex.com/tutorials/exceptions/exceptions_hierarchy.shtml</figcaption>\n</figure>\n<p>Exception은 Throwable 클래스 혹은 그 서브클래스들의 인스턴스로 표현된다. 즉, Throwable 클래스와 그의 모든 서브클래스는 모두 예외를 나타내는 클래스들이다.</p>\n<p>Throwable 클래스의 직접 서브클래스(direct subclass)로는 Exception 클래스와 Error 클래스가 있다.</p>\n<ul>\n<li>Exception 클래스는 일반적인 프로그램에서 복구를 시도할 수 있는 모든 예외의 상위 클래스이다. RuntimeException은 Exception 클래스의 직접 서브클래스이다.</li>\n<li>Error 클래스는 일반적인 프로그램에서 복구가 기대되지 않는 모든 예외의 상위 클래스이다. 대표적인 예인 <code class=\"language-text\">OutOfMemoryError</code>, <code class=\"language-text\">StackOverflowError</code>와 같이 발생하더라도 개발자가 어찌할 수 없다.</li>\n</ul>\n<p>Exception은 크게 Unchecked Exception과 Checked Exception으로 나뉜다.</p>\n<ul>\n<li>Unchecked Exception : Error 클래스, RuntimeException 클래스와 그의 서브 클래스를 말한다. 위 그림에서 빨간색에 해당하는 부분이다.</li>\n<li>Checked Exception : Unchecked Exception(RuntimeException) 클래스가 아닌 모든 Exception의 서브 클래스를 말한다. 위 그림에서 빨간색이 아닌 파란색에 해당하는 부분이다.</li>\n</ul>\n<h3>Unchecked Exception</h3>\n<p>Unchecked Exception은 <u>Error 클래스, RuntimeException 클래스와 그의 서브 클래스</u>를 말한다.</p>\n<p>컴파일 타임에 예외 처리를 위한 핸들러의 유무를 확인하지 않는다. Exception 처리가 강제되지 않아 개발자가 예외 처리 핸들러를 구현하지 않아도 된다. 물론, 원하는 경우에는 <code class=\"language-text\">catch</code>문을 사용해서 예상되는 RuntimeException 예외를 처리해줄 수 있다.</p>\n<p>Error 클래스는 시스템 레벨의 심각한 문제를 나타내며, 일반적으로 개발자가 이를 처리할 수 있는 방법이 거의 없다. 예를 들어, <code class=\"language-text\">OutOfMemoryError</code>나 <code class=\"language-text\">StackOverflowError</code>와 같은 오류는 복구가 거의 불가능한 상황을 의미한다. 이러한 이유로 개발자는 애플리케이션 코드에서 <code class=\"language-text\">Error</code> 클래스에 대한 처리를 시도하지 않는 것이 일반적이다. 그렇기에 Unchecked Exception이라고 할 때는 RuntimeException과 그 하위 클래스를 주로 의미한다.</p>\n<h3>Checked Exception</h3>\n<p>Checked Exception 클래스는 <u>Unchecked Exception 클래스가 아닌 모든 Exception 클래스</u>이다. 즉, RuntimeException 클래스 이외의 모든 Exception 클래스의 서브 클래스이다.</p>\n<p>자바는 Checked Exception에 대한 핸들러를 포함하도록 강제하여, 컴파일 타임에 Checked Exception에 대한 핸들러가 있는지 확인한다. 개발자는 예외 처리 핸들러를 반드시 포함해야 한다. <code class=\"language-text\">catch</code>문으로 처리하거나 <code class=\"language-text\">throws</code>를 이용해서 다른 곳에서 처리하도록 해야 한다. 이런 예외 처리 핸들러의 유무를 컴파일 타임에 확인함으로써 처리되지 않는 예외의 수를 줄일 수 있다.</p>\n<h2>예외 처리 방식</h2>\n<p>예외를 처리하는 방식에는 예외 복구, 예외처리 회피, 예외 전환 등 3가지 방법이 있다.</p>\n<h3>예외 복구</h3>\n<p>예외 상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 방법이다.</p>\n<p>사용자가 특정 파일을 읽으려는데 파일이 없어 <code class=\"language-text\">IOException</code>이 발생하는 경우, 다른 파일을 선택하도록 유도하는 것으로 해결할 수 있다. 혹은 DB에 접속하는데에 실패하여 <code class=\"language-text\">SQLException</code>이 발생하는 경우, 여러 번 재시도하도록 할 수도 있다.</p>\n<div class=\"gatsby-highlight\" data-language=\"java\"><pre class=\"language-java\"><code class=\"language-java\"><span class=\"token keyword\">int</span> maxretry <span class=\"token operator\">=</span> <span class=\"token constant\">MAX_RETRY</span><span class=\"token punctuation\">;</span>\n<span class=\"token keyword\">while</span> <span class=\"token punctuation\">(</span>maxretry<span class=\"token operator\">--</span> <span class=\"token operator\">></span> <span class=\"token number\">0</span><span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n   <span class=\"token keyword\">try</span> <span class=\"token punctuation\">{</span>\n\n   <span class=\"token punctuation\">}</span> <span class=\"token keyword\">catch</span> <span class=\"token punctuation\">(</span><span class=\"token class-name\">SomeException</span> e<span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n\n   <span class=\"token punctuation\">}</span> <span class=\"token keyword\">finally</span> <span class=\"token punctuation\">{</span>\n\n   <span class=\"token punctuation\">}</span>\n<span class=\"token punctuation\">}</span>\n<span class=\"token keyword\">throw</span> <span class=\"token keyword\">new</span> <span class=\"token class-name\">RetryFailedException</span><span class=\"token punctuation\">(</span><span class=\"token punctuation\">)</span><span class=\"token punctuation\">;</span>\n<span class=\"token comment\">// 출처: 토비의 스프링 3.1 Vol.1 p286</span></code></pre></div>\n<p>이처럼 사용자에게는 원하는 것처럼 동작하지 않았기 때문에 예외 상황으로 비쳐지더라도 애플리케이션에서는 정상적인 흐름에 따라 진행되어야 한다. 물론, 단순히 에러 메시지를 사용자에게 보여주는 것은 예외 복구로 볼 수 없다.</p>\n<h3>예외처리 회피</h3>\n<p>자신이 예외 처리를 하지 않고 자신을 호출한 곳에서 예외 처리를 하도록 던져버리는 것이다. <code class=\"language-text\">throws</code>문을 활용해서 예외 발생시 바로 던져버리거나, <code class=\"language-text\">catch</code>문으로 일단은 잡아 로그를 남기고 다시 예외를 던진다.</p>\n<div class=\"gatsby-highlight\" data-language=\"java\"><pre class=\"language-java\"><code class=\"language-java\"><span class=\"token keyword\">public</span> <span class=\"token keyword\">void</span> <span class=\"token function\">add</span><span class=\"token punctuation\">(</span><span class=\"token punctuation\">)</span> <span class=\"token keyword\">throws</span> <span class=\"token class-name\">SQLException</span> <span class=\"token punctuation\">{</span>\n\n<span class=\"token punctuation\">}</span></code></pre></div>\n<div class=\"gatsby-highlight\" data-language=\"java\"><pre class=\"language-java\"><code class=\"language-java\"><span class=\"token keyword\">public</span> <span class=\"token keyword\">void</span> <span class=\"token function\">add</span><span class=\"token punctuation\">(</span><span class=\"token punctuation\">)</span> <span class=\"token keyword\">throws</span> <span class=\"token class-name\">SQLException</span> <span class=\"token punctuation\">{</span>\n   <span class=\"token keyword\">try</span> <span class=\"token punctuation\">{</span>\n\n   <span class=\"token punctuation\">}</span> <span class=\"token keyword\">catch</span> <span class=\"token punctuation\">(</span><span class=\"token class-name\">SQLException</span> e<span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n      <span class=\"token comment\">// 로그 출력</span>\n      <span class=\"token keyword\">throw</span> e<span class=\"token punctuation\">;</span>\n   <span class=\"token punctuation\">}</span>\n<span class=\"token punctuation\">}</span>\n<span class=\"token comment\">// 출처: 토비의 스프링 3.1 Vol.1 p287</span></code></pre></div>\n<h3>예외 전환</h3>\n<p>예외처리 회피와 같이 <code class=\"language-text\">throws</code>를 이용해서 자신을 호출한 곳에서 예외를 처리하도록 한다. 하지만, 예외처리 회피와 달리 적절한 다른 예외로 바꾸어 던진다는 특징이 있다.</p>\n<p>예외 전환은 보통 두 가지 목적으로 사용된다.</p>\n<ol>\n<li>\n<p>발생한 예외를 그대로 던지는 것이 예외 상황을 적절히 설명하지 못하는 경우, 더 구체적인 의미를 가진 예외로 바꾸기 위해 사용한다.</p>\n<p>예를 들어, 새로운 사용자를 등록하는데 이미 같은 아이디의 사용자가 존재하는 경우 <code class=\"language-text\">SQLException</code>이 발생한다. 하지만, 외부에 그대로 <code class=\"language-text\">SQLException</code>을 던져버리면 서비스 계층에서는 왜 <code class=\"language-text\">SQLException</code>이 발생했는지, 처리할 수 있는 것인지, 어떻게 처리할 지 등을 알 수 없다. 중복된 아이디에 대한 예외는 충분히 처리할 수 있기 때문에 적절한 예외로 바꾸어 던지는 것이 좋다.</p>\n<div class=\"gatsby-highlight\" data-language=\"java\"><pre class=\"language-java\"><code class=\"language-java\"><span class=\"token keyword\">public</span> <span class=\"token keyword\">void</span> <span class=\"token function\">add</span><span class=\"token punctuation\">(</span><span class=\"token class-name\">User</span> user<span class=\"token punctuation\">)</span> <span class=\"token keyword\">throws</span> <span class=\"token class-name\">DuplicateUserIdException</span><span class=\"token punctuation\">,</span> <span class=\"token class-name\">SQLException</span> <span class=\"token punctuation\">{</span>\n   <span class=\"token keyword\">try</span> <span class=\"token punctuation\">{</span>\n\n   <span class=\"token punctuation\">}</span> <span class=\"token keyword\">catch</span> <span class=\"token punctuation\">(</span><span class=\"token class-name\">SQLException</span> e<span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n      <span class=\"token keyword\">if</span> <span class=\"token punctuation\">(</span>e<span class=\"token punctuation\">.</span><span class=\"token function\">getErrorCode</span><span class=\"token punctuation\">(</span><span class=\"token punctuation\">)</span> <span class=\"token operator\">==</span> <span class=\"token class-name\">MysqlErrorNumbers</span><span class=\"token punctuation\">.</span><span class=\"token constant\">ER_DUP_ENTRY</span><span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n         <span class=\"token keyword\">throw</span> <span class=\"token class-name\">DuplicateUserIdException</span><span class=\"token punctuation\">(</span>e<span class=\"token punctuation\">)</span><span class=\"token punctuation\">;</span>\n      <span class=\"token punctuation\">}</span> <span class=\"token keyword\">else</span> <span class=\"token punctuation\">{</span>\n         <span class=\"token keyword\">throw</span> e<span class=\"token punctuation\">;</span>\n      <span class=\"token punctuation\">}</span>\n   <span class=\"token punctuation\">}</span>\n<span class=\"token punctuation\">}</span>\n<span class=\"token comment\">// 출처: 토비의 스프링 3.1 Vol.1 p289</span></code></pre></div>\n</li>\n<li>\n<p>예외 처리를 쉽고 단순하게 만들기 위해서 사용한다.</p>\n<p>주로 예외 처리를 강제하는 Checked Exception에서 Unchecked Exception으로 바꾸는 경우에 사용한다. 예외 복구를 할 수 없거나 비즈니스적으로 의미가 없는 Checked Exception이라면 빠르게 RuntimeException으로 바꿔서 던지는 편이 좋다.</p>\n</li>\n</ol>\n<p>발생한 예외를 다른 예외로 전환하는 경우, 원래 발생한 예외를 담아 중첩 예외를 만드는 것이 좋다. 중첩 예외는 <code class=\"language-text\">getCause()</code> 메소드를 이용해서 처음 발생한 예외가 무엇인지 파악할 수 있다.</p>\n<h2>JVM에서 예외를 처리하는 방법 (예외 발생 시 동작 방법)</h2>\n<ol>\n<li>\n<p>예외가 발생하면 JVM은 Exception 객체를 생성한다.</p>\n</li>\n<li>\n<p>Exception 객체가 생성되는 과정에서 <code class=\"language-text\">fillInStackTrace</code> 메소드가 호출된다.</p>\n</li>\n<li>\n<p><code class=\"language-text\">fillInStackTrace</code> 메소드 호출로 JVM은 예외 발생 시점의 호출 스택에서 각 스택 프레임 정보를 수집하고, 해당 정보가 Exception 객체의 스택 트레이스로 채워진다.</p>\n<p>이때 수집되는 스택 프레임의 정보로는 클래스 이름, 메소드 이름, 파일 이름, 라인 번호 등등이 있다.</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">// 스택 트레이스 예시\nException in thread \"main\" java.lang.NullPointerException: Cannot load from object array because \"BOJ2563.papers\" is null\n  at BOJ2563.setUp(BOJ2563.java:45)\n  at BOJ2563.main(BOJ2563.java:15)</code></pre></div>\n</li>\n<li>\n<p>호출된 메소드의 스택을 역순으로 올라가면서(unwinding the stack) Exception을 처리할 수 있는 예외 처리 핸들러가 있는지 확인한다.</p>\n<figure>\n   <span class='gatsby-resp-image-wrapper' style='position: relative; display: block; margin-left: auto; margin-right: auto; max-width: 680px; margin-bottom: 16px;'>\n      <a class='gatsby-resp-image-link' href='/static/c71ac2635bfc89028b09808f9b2d2159/fe486/java-exception-stack-unwinding.png' style='display: block' target='_blank' rel='noopener'>\n    <span class='gatsby-resp-image-background-image' style=\"padding-bottom: 56.470588235294116%; position: relative; bottom: 0; left: 0; background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAALCAYAAAB/Ca1DAAAACXBIWXMAAAsTAAALEwEAmpwYAAABzklEQVR42n1Si3KbMBD0/39Vp51pm5km46T1A2xeBmMDAkkg3thbnbCbTJv0NIsQ6FbavVvgFn3fo6oqVKrCOIxQjcI6tmAnO+wzFx4P4GscqiOaoTU5Vz3+jgU9pmkyZEVRIM9zcD0zwfDJ+oyv9jc8Rk/Y8A0sYWMltnBPPhpVf0xYliWCIJhveCPuhg6HOsKpTxG3Z8TdjIOKUA8NknOCLMvAOUfb3m58vc6E96APFFVZacIeh+KIkM8I8lCvIwQa/WWAFNLsb5oGSql/CclD+tG0DUpZwgkcI/m782CwPL1gyy08pz/hxB5KTUjRdR0YYyaX3v94SDLTNDVgGUMhObbFDl6li6EOCNsjoi7GXnqI2QlKq7gTCiHMPAzDq4dhGJpT6ro2vozTiLTMZsgMZ54gESnyusBFDzqU9lMu5fzXQ5KcFKmW/AXL+BmrfIN1sTGSV3wLOejCsQJSSlOQcRxfq0xSXdeF7/vwPC0njtFqoxlnWCYvsLkNW+heLB24yoNTu4iY7sW6wXuxIHa6MlWLQMUxRZoGPPpL/Ng/4ddxDSvbwWJ7ONKH6meJl8vl/T58G3QAeUgg6dQeNJNXJJHWggtTxLdS74S/AXQOR8ordqqxAAAAAElFTkSuQmCC'); background-size: cover; display: block;\"></span>\n  <img class='gatsby-resp-image-image' alt='java exception stack unwinding' title='' src='/static/c71ac2635bfc89028b09808f9b2d2159/ca1dc/java-exception-stack-unwinding.png' srcset='/static/c71ac2635bfc89028b09808f9b2d2159/e7570/java-exception-stack-unwinding.png 170w,\n/static/c71ac2635bfc89028b09808f9b2d2159/f46e7/java-exception-stack-unwinding.png 340w,\n/static/c71ac2635bfc89028b09808f9b2d2159/ca1dc/java-exception-stack-unwinding.png 680w,\n/static/c71ac2635bfc89028b09808f9b2d2159/fe486/java-exception-stack-unwinding.png 768w' sizes='(max-width: 680px) 100vw, 680px' style='width:100%;height:100%;margin:0;vertical-align:middle;position:absolute;top:0;left:0;' loading='lazy' decoding='async'>\n  </a>\n    </span>\n   <figcaption>출처: https://www.geeksforgeeks.org/exceptions-in-java/</figcaption>\n</figure>\n</li>\n<li>\n<p>만약 예외 처리 핸들러를 발견하지 못하면, JVM은 해당 스레드를 종료시키며, 메인 스레드에서 예외가 처리되지 않으면 프로그램도 종료된다.</p>\n</li>\n</ol>\n<h2>예외 처리 비용</h2>\n<p>일반적으로 예외 처리 비용은 비싸다고 알려져 있다. 그럼 왜 비싸고, 얼마나 비싼 것일까?</p>\n<p>우선, Baeldung의 <a href=\"https://www.baeldung.com/java-exceptions-performance\">Performance Effects of Exceptions in Java</a> 글에서 성능 측정을 한 결과는 다음과 같았다.</p>\n<div class=\"gatsby-highlight\" data-language=\"java\"><pre class=\"language-java\"><code class=\"language-java\"><span class=\"token class-name\">Benchmark</span>                                                 <span class=\"token class-name\">Mode</span>  <span class=\"token class-name\">Cnt</span>    <span class=\"token class-name\">Score</span>   <span class=\"token class-name\">Error</span>  <span class=\"token class-name\">Units</span>\n<span class=\"token class-name\">ExceptionBenchmark</span><span class=\"token punctuation\">.</span>createExceptionWithoutThrowingIt       avgt   <span class=\"token number\">10</span>   <span class=\"token number\">16.605</span> ± <span class=\"token number\">0.988</span>  ms<span class=\"token operator\">/</span>op\n<span class=\"token class-name\">ExceptionBenchmark</span><span class=\"token punctuation\">.</span>doNotThrowException                    avgt   <span class=\"token number\">10</span>    <span class=\"token number\">0.047</span> ± <span class=\"token number\">0.006</span>  ms<span class=\"token operator\">/</span>op\n<span class=\"token class-name\">ExceptionBenchmark</span><span class=\"token punctuation\">.</span>throwAndCatchException                 avgt   <span class=\"token number\">10</span>   <span class=\"token number\">16.449</span> ± <span class=\"token number\">0.304</span>  ms<span class=\"token operator\">/</span>op\n<span class=\"token class-name\">ExceptionBenchmark</span><span class=\"token punctuation\">.</span>throwExceptionAndUnwindStackTrace      avgt   <span class=\"token number\">10</span>  <span class=\"token number\">326.560</span> ± <span class=\"token number\">4.991</span>  ms<span class=\"token operator\">/</span>op\n<span class=\"token class-name\">ExceptionBenchmark</span><span class=\"token punctuation\">.</span>throwExceptionWithoutAddingStackTrace  avgt   <span class=\"token number\">10</span>    <span class=\"token number\">1.185</span> ± <span class=\"token number\">0.015</span>  ms<span class=\"token operator\">/</span>op</code></pre></div>\n<p>위 글과 <a href=\"https://shipilev.net/blog/2014/exceptional-performance/\">The Exceptional Performance of Lil' Exception</a> 글에서의 결론은 다음과 같다.</p>\n<ol>\n<li>예외가 발생하고 처리하는 과정은 일반적인 상황에 비해 더 많은 비용이 든다. 진정으로 예외가 필요한 곳에서만 예외 처리를 사용하자.</li>\n<li>try~catch문 자체는 성능에 큰 영향을 주지 않는다.</li>\n<li>예외 처리 비용의 대부분은 <strong>스택 트레이스를 구성하는 것</strong>과 <strong>스택을 역순으로 따라가며 예외 처리 핸들러를 찾는 과정</strong>에서 발생한다.</li>\n<li>스택 트레이스를 구성하는 데에 드는 비용은 Exception 객체가 생성되는 시점의 호출 스택 깊이에 비례한다.</li>\n<li>예외를 캐싱하거나 <code class=\"language-text\">fillInStackTrace</code> 메소드를 오버라이드함으로써 최적화를 이룰 수 있다. 스택 트레이스의 정보가 생성되지 않을 수 있기 때문에 매우 특수한 경우에만 진행해야 한다.</li>\n</ol>\n<h2>(번외) Checked Exception에 대한 이슈</h2>\n<p>개발자에게 예외 처리를 강제하는 Checked Exception에 대한 이슈가 있다.</p>\n<p>무조건 예상되는 예외를 처리하도록 하여 서비스의 안정성을 도모하고자 했지만, 이를 귀찮게 느낀 개발자들은 <code class=\"language-text\">catch</code>문으로 잡아만 두고 아무런 처리도 하지 않는다거나, 의미 없이 <code class=\"language-text\">throws Exception</code>만 한다는 것이다. Checked Exception이 처음 등장했을 때와 다르게 최근에는 Unchecked Exception을 사용하자는 의견이 많아지고 있다고 한다.</p>\n<p>더 자세한 내용은 아래 글을 참고하자.</p>\n<ul>\n<li><a href=\"https://velog.io/@eastperson/Java%EC%9D%98-Checked-Exception%EC%9D%80-%EC%8B%A4%EC%88%98%EB%8B%A4-83omm70j\">https://velog.io/@eastperson/Java의-Checked-Exception은-실수다-83omm70j</a></li>\n</ul>\n<h2>참고 자료</h2>\n<ul>\n<li>토비의 스프링 3.1 Vol.1 4장</li>\n<li><a href=\"https://docs.oracle.com/javase/specs/jls/se22/jls22.pdf\">https://docs.oracle.com/javase/specs/jls/se22/jls22.pdf</a></li>\n<li><a href=\"https://docs.oracle.com/javase/specs/jvms/se22/jvms22.pdf\">https://docs.oracle.com/javase/specs/jvms/se22/jvms22.pdf</a></li>\n<li><a href=\"https://stackoverflow.com/questions/36343209/which-part-of-throwing-an-exception-is-expensive\">https://stackoverflow.com/questions/36343209/which-part-of-throwing-an-exception-is-expensive</a></li>\n<li><a href=\"https://www.baeldung.com/java-exceptions-performance\">https://www.baeldung.com/java-exceptions-performance</a></li>\n<li><a href=\"https://shipilev.net/blog/2014/exceptional-performance/\">https://shipilev.net/blog/2014/exceptional-performance/</a></li>\n<li><a href=\"https://meetup.nhncloud.com/posts/47\">https://meetup.nhncloud.com/posts/47</a></li>\n</ul>","frontmatter":{"title":"[Java] Exception에 대한 고찰","date":"August 05, 2024","tags":["Java","Exception","Checked Exception","Unchecked Exception"],"series":null},"fields":{"slug":"/java-exception/"}},"seriesList":{"edges":[{"node":{"id":"a6673bb4-177e-5ded-85b7-744a8befeed3","fields":{"slug":"/n+1-problem/"},"frontmatter":{"title":"[JPA] N+1 문제와 해결법"}}},{"node":{"id":"e6377fd6-119b-5226-ac18-d30cbc8c91a8","fields":{"slug":"/http-vs-https/"},"frontmatter":{"title":"[Network] HTTP와 HTTPS"}}},{"node":{"id":"dcdd86c3-0d41-503b-b005-fc8344a6ad53","fields":{"slug":"/aws-alb-502/"},"frontmatter":{"title":"AWS ALB가 502를 내뱉는다"}}},{"node":{"id":"019c6b3f-e536-562b-aa39-7fcc9e7c1714","fields":{"slug":"/java-exception/"},"frontmatter":{"title":"[Java] Exception에 대한 고찰"}}}]},"previous":{"fields":{"slug":"/aws-alb-502/"},"frontmatter":{"title":"AWS ALB가 502를 내뱉는다"}},"next":null},"pageContext":{"id":"019c6b3f-e536-562b-aa39-7fcc9e7c1714","series":null,"previousPostId":"dcdd86c3-0d41-503b-b005-fc8344a6ad53","nextPostId":null}},"staticQueryHashes":[],"slicesMap":{}}